#!/usr/bin/env bash
set -euo pipefail

readonly ENVIRONMENT='/etc/puppetlabs/code/environments/production'
readonly LIBRARIAN='/etc/puppetlabs/code'
readonly INPUT=$(puppet lookup --merge=deep modules "${ENVIRONMENT}")
cat << EOF > "${LIBRARIAN}/Puppetfile"
#!/usr/bin/env ruby
#^syntax detection
forge "https://forgeapi.puppetlabs.com"
EOF
COUNT=0
while IFS= read -r LINE
do
  if [[ "${COUNT}" -eq 0 ]]
  then
    COUNT=$((COUNT+1))
    continue
  fi
  IFS=': '; MODULE=($LINE); unset IFS;
  echo "mod '${MODULE[0]}', '${MODULE[1]}'" >> "${LIBRARIAN}/Puppetfile"
  ((COUNT++)) 
done <<< "${INPUT}"
cd "${LIBRARIAN}"
librarian-puppet install
puppet apply /etc/puppetlabs/code/environments/production
